using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerMovement : MonoBehaviour
{
    public float speed;
    private Rigidbody2D rb;
    private float Move;

    public float jump;

    public bool isJumping;
    public int time; 
    // Start is called before the first frame update
    void Start()
    {
        rb = GetComponent<Rigidbody2D>();
    }
    // Update is called once per frame
    void Update()
    {
      Move = Input.GetAxis("Horizontal");
      rb.velocity = new Vector2(speed * Move, rb.velocity.y);
      if (Input.GetButtonDown("Jump") && (isJumping == false || time <= 2))
      {
        rb.AddForce(new Vector2(rb.velocity.x, jump));
        Debug.Log("jump");
        time++;
      }
    }
    
    private void OnCollisionEnter2D(Collision2D other)
    {
      if (other.gameObject.CompareTag("Ground"))
      {
        isJumping = false;
        time = 0;
      }
    }

    private void OnCollisionExit2D(Collision2D other)
    {
      if (other.gameObject.CompareTag("Ground"))
      {
        isJumping = true;
        time++;
      }
    }
}
